name = raw_input("Enter your name:")
age = raw_input("Enter your age:")
education = raw_input("Enter your education:")
hobby = raw_input("Enter your hobby:")
print("NAME : " + name)
print("AGE : " + age)
print("EDUCATION : " + education)
print("HOBBY" + hobby)